### ISSUE TITLE
Bug: Periodic flushing of `EventLogger` broken.

### ISSUE THREAD

**Issue by jenshenneberg** [statsig-io/dotnet-sdk#34]
I'm testing a new feature gate in Statsig. The flag works as expected. However, I do not see anything in the "Exposure Stream" under diagnostics. When I test the flag using the build in test app, I do see events in the Exposure Stream. 

I believe the issue is related to missing `ConfigureAwait(false)` in 
https://github.com/statsig-io/dotnet-sdk/blob/main/dotnet-statsig/src/Statsig/Network/EventLogger.cs
and
https://github.com/statsig-io/dotnet-sdk/blob/main/dotnet-statsig/src/Statsig/Network/RequestDispatcher.cs

While testing locally, I can confirm that flushing only works as intended when going above 
`LoggingBufferMaxSize `
https://github.com/statsig-io/dotnet-sdk/blob/37d5e1d704a3668fe1e7ca9f4f798e6124eb17ea/dotnet-statsig/src/Statsig/StatsigOptions.cs#L28

To further support this I've added debug log lines to the `EventLogger` and did observe that the inner loop ran once or twice after startup and then never returned after [this delay](https://github.com/statsig-io/dotnet-sdk/blob/37d5e1d704a3668fe1e7ca9f4f798e6124eb17ea/dotnet-statsig/src/Statsig/Network/EventLogger.cs#L109)

For reference, please see [this](https://devblogs.microsoft.com/dotnet/configureawait-faq/#when-should-i-use-configureawaitfalse) around the usage of `ConfigureAwait(false)` in general-purpose library code.

**Comment by xinlili-statsig** [comment]
The issue on exposure events not showing up in Diagnostics tab is not an issue of dotnet SDK, but an issue on server data streaming side, the bug caused only 1 event show up for every batch of events. 
And diagnostics/log-stream service bug has been resolved

**Comment by benjamincburns** [comment]
@xinlili-statsig is it intentional that `EventLogger` would drop events when an exception is thrown by `RequestDispatcher.Fetch`? If not, perhaps the snapshot being flushed shouldn't be removed ([relevant code](https://github.com/statsig-io/dotnet-sdk/blob/cf86f45a7280259d6164bd5191783d7101be517b/dotnet-statsig/src/Statsig/Network/EventLogger.cs#L140-L151)) from the `_eventLogQueue` until after a successful flush has occurred.

I can't say definitively that's what's happened here, but if it is, we wouldn't know because of [this silent catch-all](https://github.com/statsig-io/dotnet-sdk/blob/cf86f45a7280259d6164bd5191783d7101be517b/dotnet-statsig/src/Statsig/Network/EventLogger.cs#L125-L128).

**Comment by jenshenneberg** [comment]
@xinlili-statsig: Please reopen the ticket. I do believe the periodic flushing is broken. I've created a test [here](https://github.com/statsig-io/dotnet-sdk/pull/36) that I believe shows the issue. 
I suspect the problem is missing ConfigureAwait(false) in both 
https://github.com/statsig-io/dotnet-sdk/blob/main/dotnet-statsig/src/Statsig/Network/EventLogger.cs
and 
https://github.com/statsig-io/dotnet-sdk/blob/main/dotnet-statsig/src/Statsig/Network/RequestDispatcher.cs
For context around the ConfigureAwait(false), please see [this blog](https://devblogs.microsoft.com/dotnet/configureawait-faq/)

I've updated my first comment on this ticket.

**Comment by dan-loomb** [comment]
Hey @jenshenneberg, I pulled your test and as far as I can tell, it all works if you await the delay. I have updated the test to ensure that it flushes within the 2 seconds https://github.com/statsig-io/dotnet-sdk/commit/9384bc3f847cf39d4bb137f378d5a2b897567ec9

Let me know if you still have issue with it.

Cheers

**Comment by jenshenneberg** [comment]
Hi @daniel-statsig. Thanks for the update and for fixing the test. Unfortunately, the problem still persists very much so in all our cloud environments, but my test was obviously not good enough to capture it. 
Have you had a chance to look at my comments around the missing `ConfigureAwait(false)`? I do think that it's pretty clear the code should have those added as per recommendations for async library code (Please see the blog post I linked to above for more details).

Please reopen the ticket (I suggest keeping it open until we've gotten to the bottom of this, as there clearly is a problem with the code.)

**Comment by tore-statsig** [comment]
This sounds specific to your cloud environment then, rather than specific to this library, right?  Could you elaborate on that?  What is your use case that isn't working?  So far we haven't been able to reproduce, and have only been able to confirm proper behavior via tests.  I think we don't have enough information to go on at the moment

**Comment by jenshenneberg** [comment]
@tore-statsig: No, the recommendation to use `ConfigureAwait(false)` is NOT specific to my use case/ environment. It is best practice to use this in any async library code. Please see the FAQ linked to above. There is also a blog post [here](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f).

Whether missing `ConfigureAwait(false)` causes problems or not is however depending on use case. That can be the reason why you are not seeing the issue your end. We are using the Statsig SDK from our legacy monolith running ASP.Net classic.
